language: python
dist: xenial
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip3 install -U pip
  - pip3 install -U pylint
  - pip3 install -r requirements.txt
  - cp settings.py.sample settings.py
script:
  - pylint autocomplete.py
  - pylint dashboard.py
  - pylint isin.py
  - pylint reporter.py
  - pylint lib/*.py

